services:
  redis:
    image: redis:7-alpine
    command: redis-server --loglevel warning
    restart: unless-stopped
    ports:
      - "8000:8000"

  api:
    build: ./API
    restart: unless-stopped
    network_mode: "service:redis"
    env_file:
      - ./API/.env
    depends_on:
      - redis
      - server_wallet
    volumes:
      - ./API/data:/app/data

  nft:
    build: ./NFT
    restart: unless-stopped
    ports:
      - "8100:8000"

  tg_bot:
    build: ./Tg_bot
    restart: unless-stopped
    env_file:
      - ./Tg_bot/.env

  crypto_admin:
    build: ./Crypto_admin
    restart: unless-stopped
    network_mode: "service:redis"
    env_file:
      - ./Crypto_admin/.env
    depends_on:
      - redis
      - server_wallet

  server_wallet:
    build: ./Server_wallet
    restart: unless-stopped
    network_mode: "service:redis"
    env_file:
      - ./Server_wallet/.env
    depends_on:
      - redis
    volumes:
      - ./Server_wallet/data:/app/data

