user www-data;
worker_processes auto;
pid /run/nginx.pid;

error_log /var/log/nginx/error.log;

events {
        worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type  application/octet-stream;

    gzip on;
    sendfile on;

    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    ssl_certificate /etc/letsencrypt/live/biptoken.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/biptoken.xyz/privkey.pem;

    add_header 'Access-Control-Allow-Origin' * always;

    server {
        listen 443 ssl;
        server_name  www.biptoken.xyz;


        location ~* \.(json|png|jpg|txt|ico|webp|gif)$ {
            return 301 https://static.biptoken.xyz$uri$is_args$args;
        }

        location / {
            return 302 https://www.app.biptoken.xyz$uri$is_args$args;
        }
    }
    server {
        listen 443 ssl;
        server_name  biptoken.xyz;
        return 302 https://www.biptoken.xyz$uri$is_args$args;
    }
    server {
        listen 443 ssl;
        server_name api.biptoken.xyz;

        location / {
            proxy_pass         http://127.0.0.1:8000/;
            proxy_redirect     off;
        }
    }
    server {
        listen 443 ssl;
        server_name www.app.biptoken.xyz;

        location / {
            root /usr/dev/BIP/Web_app/dist/;
            try_files $uri $uri/ /index.html;
        }
    }
    server {
        listen 443 ssl;
        server_name  app.biptoken.xyz;
        return 302 https://www.app.biptoken.xyz$uri$is_args$args;
    }
    server {
        listen 443 ssl;
        server_name nft.biptoken.xyz;

        proxy_buffering     on;
        proxy_redirect      off;

        location / {
            proxy_pass         http://127.0.0.1:8100/;
        }
        location ~* \.(jpg|jpeg|gif|png)$ {
            expires   24h;
            root         /usr/dev/BIP/NFT/static/;
        }
    }
    server {
        listen 443 ssl;
        server_name static.biptoken.xyz;

        location ~* (^|$host)\/?(json|png|jpg|txt|ico|webp|gif|)\/(?<path>.*\.(?<ext>json|png|jpg|txt|ico|webp|gif))(\?|$) {
            expires   24h;
            alias    /usr/dev/BIP/Static/$ext/$path;

        }
    }
    server {
        listen 80;
        return 301 https://$host$uri$is_args$args;
    }
}