user www-data;
worker_processes auto;
pid /run/nginx.pid;


error_log /var/log/nginx/error.log;

events {
        worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type  application/octet-stream;

    gzip on;
    sendfile on;

    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    ssl_certificate /etc/letsencrypt/live/biptoken.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/biptoken.xyz/privkey.pem;

    add_header 'Access-Control-Allow-Origin' * always;

    server {
        listen 443 ssl;
        server_name  biptoken.xyz www.biptoken.xyz;

        return 302 https://app.biptoken.xyz;
    }
    server {
        listen 443 ssl;
        server_name api.biptoken.xyz www.api.biptoken.xyz;

        location / {
            proxy_pass         http://127.0.0.1:8000/;
            proxy_redirect     off;
        }
    }
    server {
        listen 443 ssl;
        server_name app.biptoken.xyz www.app.biptoken.xyz;

        location / {
            root /usr/dev/BIP/Web_app/src/;
            try_files $uri $uri $uri/ /index.html;
        }
    }

    server {
        listen 80;
        return 302 https://$host$request_uri;
    }
}