services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
      - "8000:8000"

  api:
    build: .
    network_mode: "service:redis"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./data:/app/data